name: Build and Deploy to Azure App Service

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout Code
      uses: actions/checkout@v4

    # Step 2: Set up Python environment (if needed)
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    # Step 3: Install dependencies and build
    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    # Step 4: Create the tar.gz archive (Simulate your existing build process)
    - name: Create output.tar.gz
      run: tar -czvf output.tar.gz ./*

    # Step 5: Extract and Deploy to Azure App Service
    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v3
      with:
        app-name: app-ocrsolution
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
        package: output.tar.gz

    # Step 6: Extract the build on the App Service
    - name: Extract Build on App Service
      run: |
        curl -X POST \
        -u ${{ secrets.APP_SERVICE_USERNAME }}:${{ secrets.APP_SERVICE_PASSWORD }} \
        -d '{"command": "tar -xvzf output.tar.gz -C /home/site/wwwroot"}' \
        https://app-ocrsolution-argus.scm.azurewebsites.net/api/command
